/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypesRouteImport } from './routes/types'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonIdRouteImport } from './routes/pokemon.$id'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as ApiPublicSyncPokemonRouteImport } from './routes/api/public/sync-pokemon'

const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIdRoute = PokemonIdRouteImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)
const ApiPublicSyncPokemonRoute = ApiPublicSyncPokemonRouteImport.update({
  id: '/api/public/sync-pokemon',
  path: '/api/public/sync-pokemon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/items': typeof ItemsRouteWithChildren
  '/types': typeof TypesRoute
  '/items/$id': typeof ItemsIdRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/api/public/sync-pokemon': typeof ApiPublicSyncPokemonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/items': typeof ItemsRouteWithChildren
  '/types': typeof TypesRoute
  '/items/$id': typeof ItemsIdRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/api/public/sync-pokemon': typeof ApiPublicSyncPokemonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/items': typeof ItemsRouteWithChildren
  '/types': typeof TypesRoute
  '/items/$id': typeof ItemsIdRoute
  '/pokemon/$id': typeof PokemonIdRoute
  '/api/public/sync-pokemon': typeof ApiPublicSyncPokemonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/items'
    | '/types'
    | '/items/$id'
    | '/pokemon/$id'
    | '/api/public/sync-pokemon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/items'
    | '/types'
    | '/items/$id'
    | '/pokemon/$id'
    | '/api/public/sync-pokemon'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/items'
    | '/types'
    | '/items/$id'
    | '/pokemon/$id'
    | '/api/public/sync-pokemon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  TypesRoute: typeof TypesRoute
  PokemonIdRoute: typeof PokemonIdRoute
  ApiPublicSyncPokemonRoute: typeof ApiPublicSyncPokemonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/api/public/sync-pokemon': {
      id: '/api/public/sync-pokemon'
      path: '/api/public/sync-pokemon'
      fullPath: '/api/public/sync-pokemon'
      preLoaderRoute: typeof ApiPublicSyncPokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ItemsRoute: ItemsRouteWithChildren,
  TypesRoute: TypesRoute,
  PokemonIdRoute: PokemonIdRoute,
  ApiPublicSyncPokemonRoute: ApiPublicSyncPokemonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
